version: '2.1'
orbs:
  cypress: cypress-io/cypress@3.3.1
workflows:
  use-my-orb:
    jobs:
      - cypress/run:
          cypress-command: npx cypress run --browser chrome
          install-browsers: true
          # start-command: npm run start:dev
      steps:
        - run:
  #...
  # run tests and store XML files to a subdirectory, for example, test-results
  #...
        - store_test_results:
          path: test-results
